import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import TaskController from '../controller/TaskController'
import { useEffect, useState } from 'react';
import axios from 'axios';



export default function Home() {

  const [isLoading, setLoading] = useState(true)
  const [tasks, setTasks] = useState();


  useEffect(() => {
    fetch('https://alansiq-projectify-backend.herokuapp.com/tasks').then((res) => res.json()).then((tasklist) => {
      setTasks(tasklist)
      setLoading(false)
    });
    ;
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? <p>Loading...</p> : tasks.map((t, i) => <p key={i}>{t.title}</p>)}
      <p>Hello world</p>
    </div>
  )
}






